name: Helm Testing

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
        default: staging
      test_deploy:
        required: false
        type: boolean
        default: false
    secrets:
      github_access_token:
        required: false

jobs:
  chart-helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{secrets.github_access_token}}   

      - name: Chart Helm Linter
        id: linter
        run: helm lint ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml

  chart-helm-test-deploy:
    needs: chart-helm-test
    if: test_deploy
    uses: alice-biometrics/actions/.github/workflows/chart-helm-test-deploy.yml@main
    with:
      chart: ${{inputs.chart}}
      environment: ${{inputs.environment}}
    secrets:
      github_access_token: ${{secrets.github_access_token}} 