name: Helm Update Docker Image

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
        default: staging
      version:
        required: true
        type: string 
    secrets:
      github_access_token:
        required: false

jobs:
  chart-helm-update-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - name: Backup Reference Docker Image
        run: |
          echo "Backup reference docker image on chart ${{inputs.chart}} (environment: ${{inputs.environment}}) before to go to ${{inputs.version}}"
          cd ${{inputs.chart}}/chart
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"
          cp values-${{inputs.environment}}.yaml values-${{inputs.environment}}.yaml.old
          git add -u
          git commit -m "ENH. ${{inputs.chart}}. Backup reference image before to update to ${{inputs.version}} (${{inputs.environment}})"

      - name: Update Docker Image
        run: |
          echo "Updating docker image on chart ${{inputs.chart}} (environment: ${{inputs.environment}}) to ${{inputs.version}}"
          sed -ri 's/^(\s*)(tag:.*$)/\1tag: ${{inputs.version}}/' values-${{inputs.environment}}.yaml
          git add -u
          git commit -m "ENH. ${{inputs.chart}}. Update image to ${{inputs.version}} (${{inputs.environment}})"

      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.github_access_token}} 
          repository: alice-biometrics/alice-k8s-cloud