name: Helm Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
        default: staging
      gke_zone:
        required: true 
        type: string
        default: europe-west1-b
      gke_project:
        required: true
        type: string
        default: alice-cloud-staging
    secrets:
      github_access_token:
        required: false
      gke_key:
        required: false

jobs:
  chart-helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id:  ${{inputs.gke_project}}
          service_account_key: ${{ secrets.gke_key }}
          export_default_credentials: true

      - name: Gcloud Auth
        run: gcloud auth configure-docker

      - name: Helm Deploy
        run: |
          gcloud container clusters get-credentials alice-cluster-${{inputs.environment}} --zone ${{inputs.gke_zone}} --project ${{inputs.gke_project}}
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml --dry-run --namespace ${{inputs.environment}}

      # - name: Rollback
      #   if: failure()
      #   run: |
      #     kubectl -n ${NAMESPACE} rollout undo ${DEPLOYMENT}          

      # - name: Chart Helm Linter
      #   id: linter
      #   run: helm lint ${{github.event.inputs.chart}}/chart/ -f ${{github.event.inputs.chart}}/chart/${{github.event.inputs.environment}}

      # - name: Create kind cluster for testing Chart
      #   uses: helm/kind-action@v1.2.0

      # - name: Chart Helm Deploy
      #   run: helm install ${{github.event.inputs.chart}} ${{github.event.inputs.chart}}/chart/ -f ${{github.event.inputs.chart}}/chart/${{github.event.inputs.environment}}