name: Helm Test And Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
      version:
        required: true
        type: string
      test_deploy:
        required: false
        type: boolean
        default: false
    secrets:
      github_access_token:
        required: false
      gke_key:
        required: true
      gke_project:
        required: true
      gke_zone:
        required: true 
      gke_cluster_prefix:
        required: true

jobs:
  chart-helm-update:
    uses: alice-biometrics/actions/.github/workflows/chart-helm-update-docker-image.yml@main
    with:
      chart: ${{inputs.chart}}
      environment: ${{inputs.environment}}
      version: ${{inputs.version}}
    secrets:
      github_access_token: ${{secrets.github_access_token}} 

  chart-helm-test:
    needs: chart-helm-update
    uses: alice-biometrics/actions/.github/workflows/chart-helm-test.yml@main
    with:
      chart: ${{inputs.chart}}
      environment: ${{inputs.environment}}
      test_deploy: ${{inputs.test_deploy}}
    secrets:
      github_access_token: ${{secrets.github_access_token}} 

  chart-helm-deploy:
    needs: chart-helm-test
    uses: alice-biometrics/actions/.github/workflows/chart-helm-deploy.yml@main
    with:
      chart: ${{inputs.chart}}
      environment: ${{inputs.environment}}
    secrets:
      github_access_token: ${{secrets.github_access_token}} 
      gke_zone: ${{secrets.gke_zone}}
      gke_project: ${{secrets.gke_project}}
      gke_key: ${{secrets.gke_key}}
      gke_cluster_prefix: ${{secrets.gke_cluster_prefix}}