name: Helm Test Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
        default: staging
    secrets:
      github_access_token:
        required: false

jobs:
  chart-helm-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - name: Create kind cluster for testing Chart
        uses: helm/kind-action@v1.2.0

      - name: Chart Helm Deploy
        run: helm install ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml