name: Helm Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
        default: staging
    secrets:
      github_access_token:
        required: true
      gke_key:
        required: true
      gke_project:
        required: true
      gke_zone:
        required: true 
      gke_cluster_prefix:
        required: true

jobs:
  chart-helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id:  ${{secrets.gke_project}}
          service_account_key: ${{ secrets.gke_key }}
          export_default_credentials: true

      - name: Gcloud Auth
        run: gcloud auth configure-docker

      - name: Helm Deploy
        id: helm-deploy
        run: |
          gcloud container clusters get-credentials ${{secrets.gke_cluster_prefix}}-${{inputs.environment}} --zone ${{secrets.gke_zone}} --project ${{secrets.gke_project}}
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml --wait --atomic --namespace ${{inputs.environment}}

      - name: Rollback Helm Deploy
        if:  ${{ steps.helm-deploy.outcome == 'failure' }}
        run: |
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml.old --wait --atomic --namespace ${{inputs.environment}}        

      - name: Restore Reference Docker Image
        if:  ${{ steps.helm-deploy.outcome == 'failure' }}
        run: |
          cp ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml.old ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml
          rm ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml.old
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"          
          git add -u 

      - name: Purge old Reference Image
        if:  ${{ steps.helm-deploy.outcome == 'sucess' }}
        run: |
          rm ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml.old
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"          
          git add -u

      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.github_access_token}} 
          repository: alice-biometrics/alice-k8s-cloud