name: Helm Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string
        description: Chart to update and then deploy.
      environment:
        required: true
        type: string
        description: Environment to deploy
      version:
        required: true
        type: string
        description: Image Version to deploy
      test_deploy:
        required: false
        type: boolean
        default: false
        description:  Test deployment chart using kind.
      helm_deploy_args:
        required: false
        type: string
        description: Add some args to helm deploy command (e.g use `--dry-run` to test your workflow)
        default: "--install --wait --atomic --debug"
    secrets:
      github_access_token:
        required: false
      gke_key:
        required: true
      gke_project:
        required: true
      gke_zone:
        required: true 
      gke_cluster_prefix:
        required: true

jobs:
  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - name: Update Docker Image
        working-directory: ${{inputs.chart}}/chart
        run: |
          echo "Updating docker image on chart ${{inputs.chart}} (environment: ${{inputs.environment}}) to ${{inputs.version}}"
          sed -ri 's/^(\s*)(tag:.*$)/\1tag: ${{inputs.version}}/' values-${{inputs.environment}}.yaml

      - name: Chart Helm Linter
        id: linter
        run: helm lint ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml

      - name: Install Helm Kube-score
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kubectl: '1.17.1'
          helm: '3.8.0'
          kube-score: '1.13.0'

      - name: Launch Helm Kube-score          
        run: helm template ${{inputs.chart}}/chart -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml | kube-score score -
        continue-on-error: true        

      - name: Create kind cluster for testing Chart
        if: ${{ inputs.test_deploy }}
        uses: helm/kind-action@v1.2.0

      - name: Chart Helm Deploy
        if: ${{ inputs.test_deploy }}
        run: helm install ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gke_key }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Helm Deploy
        id: helm-deploy
        run: |
          gcloud container clusters get-credentials ${{secrets.gke_cluster_prefix}}-${{inputs.environment}} --zone ${{secrets.gke_zone}} --project ${{secrets.gke_project}}
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml ${{inputs.helm_deploy_args}} --namespace ${{inputs.environment}}

      - name: Set Repo Alice Biometrics  
        run: helm repo add alice-biometrics --username "${{ secrets.github_access_token }}" --password "${{ secrets.github_access_token }}" "https://raw.githubusercontent.com/alice-biometrics/helm-chart-repository/main/"

      - name: Rollback Helm Deploy
        if:  ${{ steps.helm-deploy.outcome == 'failure' }}
        run: |
          cd helm-chart-repository
          helm pull --devel --untar alice-biometrics/${{inputs.chart}}        
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/ -f ${{inputs.chart}}/values-${{inputs.environment}}.yaml ${{inputs.helm_deploy_args}} --namespace ${{inputs.environment}}
          echo "::error ::Failure on Helm Deploy"

      - name: Commit changes
        if: ${{ steps.helm-deploy.outcome == 'success' }}
        working-directory: ${{inputs.chart}}/chart
        run: |
          git pull
          sed -ri 's/^(\s*)(version:.*$)/\1version: ${{inputs.version}}/' Chart.yaml
          helm package .
          git add values-${{inputs.environment}}.yaml
          git add Chart.yaml          
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"
          git commit -m "ENH. ${{inputs.chart}}. Update image to ${{inputs.version}} (${{inputs.environment}})"

      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.github_access_token}} 
          repository: alice-biometrics/alice-k8s-cloud