name: Helm Rollback

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
    secrets:
      github_access_token:
        required: false
      gke_key:
        required: true
      gke_project:
        required: true
      gke_zone:
        required: true
      gke_cluster_prefix:
        required: true

jobs:
  helm-rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/helm-chart-repository
          token: ${{ secrets.github_access_token}}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gke_key }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Set Repo Alice Biometrics
        run: helm repo add alice-biometrics --username "${{ secrets.github_access_token }}" --password "${{ secrets.github_access_token }}" "https://raw.githubusercontent.com/alice-biometrics/helm-chart-repository/main/"

      - name: Rollback Helm Deploy
        id: helm-rollback
        run: |
          gcloud container clusters get-credentials ${{secrets.gke_cluster_prefix}}-${{inputs.environment}} --zone ${{secrets.gke_zone}} --project ${{secrets.gke_project}}
          helm pull --devel --untar alice-biometrics/${{inputs.chart}}
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/ -f ${{inputs.chart}}/values-${{inputs.environment}}.yaml --install --wait --atomic --namespace ${{inputs.environment}} 