name: Helm Deploy

on:
  workflow_call:
    inputs:
      chart:
        required: true
        type: string 
      environment:
        required: true
        type: string 
      version:
        required: true
        type: string
      test_deploy:
        required: false
        type: boolean
        default: false
    secrets:
      github_access_token:
        required: false
      gke_key:
        required: true
      gke_project:
        required: true
      gke_zone:
        required: true 
      gke_cluster_prefix:
        required: true

jobs:
  chart-helm-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   

      - name: Update Docker Image
        run: |
          echo "Updating docker image on chart ${{inputs.chart}} (environment: ${{inputs.environment}}) to ${{inputs.version}}"
          cd ${{inputs.chart}}/chart
          sed -ri 's/^(\s*)(tag:.*$)/\1tag: ${{inputs.version}}/' values-${{inputs.environment}}.yaml
          git add -u
          git config --global user.email "dev@alicebiometrics.com"
          git config --global user.name "Alice Biometrics"
          git commit -m "ENH. ${{inputs.chart}}. Update image to ${{inputs.version}} (${{inputs.environment}})"
      - name: Push changes
        uses: alice-biometrics/github-push-action@master
        with:
          github_token: ${{ secrets.github_access_token}} 
          repository: alice-biometrics/alice-k8s-cloud

  chart-helm-test:
    needs: chart-helm-update
    runs-on: ubuntu-latest
    steps:
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0
    - name: Checkout Helm Chart Repo
      uses: actions/checkout@v2
      with:
        repository: alice-biometrics/alice-k8s-cloud
        token: ${{secrets.github_access_token}}   
    - name: Chart Helm Linter
      id: linter
      run: helm lint ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml
    - name: Create kind cluster for testing Chart
      if: ${{ inputs.test_deploy }}
      uses: helm/kind-action@v1.2.0
    - name: Chart Helm Deploy
      if: ${{ inputs.test_deploy }}
      run: helm install ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml


  chart-helm-deploy:
    needs: chart-helm-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Checkout Helm Chart Repo
        uses: actions/checkout@v2
        with:
          repository: alice-biometrics/alice-k8s-cloud
          token: ${{ secrets.github_access_token}}   
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id:  ${{secrets.gke_project}}
          service_account_key: ${{ secrets.gke_key }}
          export_default_credentials: true
      - name: Gcloud Auth
        run: gcloud auth configure-docker
      - name: Helm Deploy
        run: |
          gcloud container clusters get-credentials ${{secrets.gke_cluster_prefix}}-${{inputs.environment}} --zone ${{secrets.gke_zone}} --project ${{secrets.gke_project}}
          helm upgrade ${{inputs.chart}} ${{inputs.chart}}/chart/ -f ${{inputs.chart}}/chart/values-${{inputs.environment}}.yaml --dry-run --namespace ${{inputs.environment}}
